import { useMemo } from 'react';
import Link from 'next/link';
import SeoHead from '../components/SeoHead';
import { SEO_PAGES } from '../config/seo';
import { buildBreadcrumbSchema, buildWebPageSchema, getBaseSchemas, getSchemaSiteUrl } from '../utils/schema';

export default function TermsPage() {
  const seoJsonLd = useMemo(() => {
    const siteUrl = getSchemaSiteUrl();
    const base = getBaseSchemas(siteUrl);
    return [
      base.organization,
      base.webSite,
      buildBreadcrumbSchema(siteUrl, [
        { name: 'Home', path: '/' },
        { name: 'Terms of Service', path: SEO_PAGES.terms.path },
      ]),
      buildWebPageSchema({
        siteUrl,
        path: SEO_PAGES.terms.path,
        title: SEO_PAGES.terms.title,
        description: SEO_PAGES.terms.description,
      }),
    ];
  }, []);

  return (
    <>
      <SeoHead
        title={SEO_PAGES.terms.title}
        description={SEO_PAGES.terms.description}
        path={SEO_PAGES.terms.path}
        jsonLd={seoJsonLd}
      />

      <div className="min-h-screen py-8 px-4 lg:px-6 relative z-10 flex items-start justify-center bg-neural-bg">
        <div className="max-w-3xl w-full mx-auto">
          <div className="glass-ui">
            <header className="neural-header">
              <div className="flex flex-col gap-1">
                <Link href="/" className="neural-brand font-mono hover:text-neural-accent transition-colors">
                  <span className="text-neural-muted">{'// '}</span>GROKIFY_PROMPT <span className="text-neural-accent">v2.0</span>
                </Link>
                <p className="text-xs text-neural-dim font-mono uppercase tracking-wider">
                  Terms of service
                </p>
              </div>
              <div className="neural-status">
                <span className="neural-status-dot" />
                SYSTEM ONLINE
              </div>
            </header>

            <main className="p-6 space-y-6">
              <nav aria-label="Breadcrumb" className="text-xs font-mono uppercase tracking-wider text-neural-dim">
                <ol className="flex flex-wrap items-center gap-2">
                  <li>
                    <Link href="/" className="hover:text-neural-accent transition-colors">
                      Home
                    </Link>
                  </li>
                  <li aria-hidden="true">/</li>
                  <li aria-current="page" className="text-neural-white">
                    Terms
                  </li>
                </ol>
              </nav>

              <div className="neural-section">
                <h1 className="neural-section-header">01 // TERMS_OF_SERVICE</h1>
                <div className="space-y-3 text-sm leading-relaxed text-neural-muted">
                  <p>
                    Last updated: <time dateTime="2026-01-05">January 5, 2026</time>
                  </p>
                  <p>
                    By using GROKIFY_PROMPT, you agree to these terms. If you do not agree, please discontinue use.
                  </p>
                </div>
              </div>

              <div className="neural-section">
                <h2 className="neural-section-header">02 // ACCEPTABLE_USE</h2>
                <div className="space-y-3 text-sm leading-relaxed text-neural-muted">
                  <ul className="list-disc pl-5 space-y-1">
                    <li>Do not use the service for unlawful, harmful, or abusive content.</li>
                    <li>Do not attempt to disrupt the service, bypass rate limits, or probe for vulnerabilities.</li>
                    <li>Do not submit sensitive personal data in prompts.</li>
                  </ul>
                </div>
              </div>

              <div className="neural-section">
                <h2 className="neural-section-header">03 // AI_OUTPUTS</h2>
                <div className="space-y-3 text-sm leading-relaxed text-neural-muted">
                  <p>
                    Outputs are generated by third-party AI providers. GROKIFY_PROMPT does not guarantee accuracy,
                    completeness, or suitability for a specific purpose.
                  </p>
                  <p>
                    You are responsible for how you use generated prompts and for complying with the rules of any
                    downstream AI tools and platforms.
                  </p>
                </div>
              </div>

              <div className="neural-section">
                <h2 className="neural-section-header">04 // WARRANTY_AND_LIABILITY</h2>
                <div className="space-y-3 text-sm leading-relaxed text-neural-muted">
                  <p>
                    The service is provided &quot;as is&quot; without warranties of any kind. To the maximum extent
                    permitted by law, we are not liable for any indirect or consequential damages arising from your use
                    of the service.
                  </p>
                </div>
              </div>

              <div className="neural-section">
                <h2 className="neural-section-header">05 // PRIVACY</h2>
                <div className="space-y-2 text-sm leading-relaxed text-neural-muted">
                  <p>
                    For information about data handling, see the{' '}
                    <Link href="/privacy" className="text-neural-accent hover:underline">
                      privacy policy
                    </Link>
                    .
                  </p>
                </div>
              </div>
            </main>
          </div>

          <footer className="text-center py-6 space-y-2">
            <div className="neural-divider mb-4" />
            <nav aria-label="Footer links" className="flex flex-wrap items-center justify-center gap-3 text-xs font-mono uppercase tracking-wider text-neural-dim">
              <Link href="/" className="hover:text-neural-accent transition-colors">
                HOME
              </Link>
              <Link href="/privacy" className="hover:text-neural-accent transition-colors">
                PRIVACY
              </Link>
              {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
              <a href="/sitemap.xml" className="hover:text-neural-accent transition-colors">
                SITEMAP
              </a>
            </nav>
          </footer>
        </div>
      </div>
    </>
  );
}

